### PR TITLE
installing on macOS

### PR DESCRIPTION
**Pull request by freeboson**

### CODE REVIEW

**Comment by michaelhb** [comment]
That's awesome, I never managed to get OSX working!

**Comment by michaelhb** [comment]
@innisfree Assuming superplot is now OSX-friendly, do we want to update the user manual or would that be a giant hassle?

**Comment by andrewfowlie** [comment]
Thanks Sujeet.

We can update the arXiv version very easily. Do we know why it didn't work
before but works now? New Mac OSX? Better brew source of pygtk available?

On 29 Nov 2016 4:56 PM, "michaelhb" <notifications@github.com> wrote:
>
> @innisfree Assuming superplot is now OSX-friendly, do we want to update
the user manual or would that be a giant hassle?

**Comment by freeboson** [comment]
By default, homebrew does not install matplotlib with pygtk support. You
have to do --with-pygtk

**Pull request merged**
